/* asteroids.js — Juegos XP. Código original sin cambios (solo separado en archivos). */
(function(){let canvas=document.getElementById(`astC`),ctx=canvas.getContext(`2d`),W=canvas.width,H=canvas.height,KEY={left:!1,right:!1,thrust:!1,fire:!1},ship=newShip(),bullets=[],asteroids=[],particles=[],score=0,lives=3,level=1,best=0,gameOver=!1,paused=!1,running=!1,raf=null,fireCooldown=0;try{best=parseInt(localStorage.getItem(`astBest`)||`0`,10)||0}catch{}function rnd(a,b){return a+Math.random()*(b-a)}function wrap(p){p.x<0&&(p.x+=W),p.x>W&&(p.x-=W),p.y<0&&(p.y+=H),p.y>H&&(p.y-=H)}function newShip(){return{x:W/2,y:H/2,vx:0,vy:0,angle:-Math.PI/2,radius:8}}function makeAsteroid(x,y,size){
// size: 3=big, 2=medium, 1=small
let speed=rnd(.3,1)*(1+(level-1)*.12)*(4-size)/3+.2,ang=rnd(0,Math.PI*2),radius=size===3?22:size===2?12:6,verts=8+Math.floor(rnd(0,4)),offsets=[];for(let i=0;i<verts;i++)offsets.push(rnd(.7,1.3));return{x,y,vx:Math.cos(ang)*speed,vy:Math.sin(ang)*speed,radius,size,rot:rnd(0,Math.PI*2),rotSpeed:rnd(-.02,.02),offsets}}function spawnLevel(){asteroids=[];let count=3+level;for(let i=0;i<count;i++){let x,y;do x=rnd(0,W),y=rnd(0,H);while(Math.hypot(x-W/2,y-H/2)<50);asteroids.push(makeAsteroid(x,y,3))}}function resetGame(){ship=newShip(),bullets=[],particles=[],score=0,lives=3,level=1,gameOver=!1,paused=!1,fireCooldown=0,spawnLevel(),updateHUD(),document.getElementById(`astGameOver`).classList.remove(`show`)}function updateHUD(){document.getElementById(`ast-scoreEl`).textContent=` `+score,document.getElementById(`ast-levelEl`).textContent=` `+level,document.getElementById(`ast-livesEl`).textContent=String(lives)}function addParticles(x,y,n,color){for(let i=0;i<n;i++){let ang=rnd(0,Math.PI*2),spd=rnd(.5,3);particles.push({x,y,vx:Math.cos(ang)*spd,vy:Math.sin(ang)*spd,life:rnd(15,35),color:color||`#0ff`})}}function splitAsteroid(a){if(vibrate(15),addParticles(a.x,a.y,a.size===3?14:a.size===2?9:5,`#0ff`),score+=a.size===3?20:a.size===2?50:100,updateHUD(),a.size>1)for(let i=0;i<2;i++){let na=makeAsteroid(a.x,a.y,a.size-1);na.vx+=a.vx*.4,na.vy+=a.vy*.4,asteroids.push(na)}}function shipDestroyed(){vibrate([0,40,60,40]),addParticles(ship.x,ship.y,24,`#fff`),lives--,updateHUD(),lives<=0?endGame():(ship=newShip(),ship.invuln=90)}function endGame(){if(gameOver=!0,score>best){best=score;try{localStorage.setItem(`astBest`,String(best))}catch{}}document.getElementById(`astFinalScore`).textContent=`Puntuación: `+score+`  ·  Mejor: `+best,document.getElementById(`astGameOver`).classList.add(`show`)}function fire(){fireCooldown>0||gameOver||(fireCooldown=10,bullets.push({x:ship.x+Math.cos(ship.angle)*ship.radius,y:ship.y+Math.sin(ship.angle)*ship.radius,vx:Math.cos(ship.angle)*4+ship.vx*.5,vy:Math.sin(ship.angle)*4+ship.vy*.5,life:60}),vibrate(8))}function update(){if(!(paused||gameOver)){KEY.left&&(ship.angle-=.07),KEY.right&&(ship.angle+=.07),KEY.thrust&&(ship.vx+=Math.cos(ship.angle)*.08,ship.vy+=Math.sin(ship.angle)*.08,addParticles(ship.x-Math.cos(ship.angle)*ship.radius,ship.y-Math.sin(ship.angle)*ship.radius,1,`#fa0`)),KEY.fire&&fire(),fireCooldown>0&&fireCooldown--,ship.vx*=.99,ship.vy*=.99,ship.x+=ship.vx,ship.y+=ship.vy,wrap(ship),ship.invuln>0&&ship.invuln--;
// bullets
for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];if(b.x+=b.vx,b.y+=b.vy,b.life--,wrap(b),b.life<=0){bullets.splice(i,1);continue}}
// asteroids
for(let a of asteroids)a.x+=a.vx,a.y+=a.vy,a.rot+=a.rotSpeed,wrap(a);
// particles
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx,p.y+=p.vy,p.life--,p.life<=0&&particles.splice(i,1)}
// bullet-asteroid collisions
for(let i=asteroids.length-1;i>=0;i--){let a=asteroids[i];for(let j=bullets.length-1;j>=0;j--){let b=bullets[j];if(Math.hypot(a.x-b.x,a.y-b.y)<a.radius){bullets.splice(j,1),asteroids.splice(i,1),splitAsteroid(a);break}}}
// ship-asteroid collisions
if(!ship.invuln){for(let a of asteroids)if(Math.hypot(a.x-ship.x,a.y-ship.y)<a.radius+ship.radius*.7){shipDestroyed();break}}
// level cleared
asteroids.length===0&&!gameOver&&(level++,score+=100,updateHUD(),spawnLevel())}}function drawShip(){ship.invuln&&Math.floor(ship.invuln/4)%2==0||(ctx.save(),ctx.translate(ship.x,ship.y),ctx.rotate(ship.angle),ctx.strokeStyle=`#0ff`,ctx.lineWidth=1.5,ctx.beginPath(),ctx.moveTo(ship.radius*1.4,0),ctx.lineTo(-ship.radius,ship.radius*.8),ctx.lineTo(-ship.radius*.5,0),ctx.lineTo(-ship.radius,-ship.radius*.8),ctx.closePath(),ctx.stroke(),ctx.restore())}function drawAsteroid(a){ctx.save(),ctx.translate(a.x,a.y),ctx.rotate(a.rot),ctx.strokeStyle=`#0ff`,ctx.lineWidth=1.2,ctx.beginPath();let n=a.offsets.length;for(let i=0;i<n;i++){let ang=i/n*Math.PI*2,r=a.radius*a.offsets[i],x=Math.cos(ang)*r,y=Math.sin(ang)*r;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.closePath(),ctx.stroke(),ctx.restore()}function draw(){
// stars
ctx.fillStyle=`#000`,ctx.fillRect(0,0,W,H),ctx.fillStyle=`#055`;for(let i=0;i<20;i++){let x=i*53%W,y=i*97%H;ctx.fillRect(x,y,1,1)}for(let a of asteroids)drawAsteroid(a);ctx.fillStyle=`#0ff`;for(let b of bullets)ctx.fillRect(b.x-1,b.y-1,2,2);for(let p of particles)ctx.fillStyle=p.color,ctx.globalAlpha=Math.max(0,p.life/30),ctx.fillRect(p.x-1,p.y-1,2,2);ctx.globalAlpha=1,gameOver||drawShip()}function loop(){update(),draw(),raf=requestAnimationFrame(loop)}function startGame(){document.getElementById(`astStartScreen`).style.display=`none`,document.getElementById(`astGameOver`).classList.remove(`show`),resetGame(),running=!0,raf&&cancelAnimationFrame(raf),raf=requestAnimationFrame(loop)}
// ===== Controls =====
function setKey(k,v){KEY[k]=v}(function(){let jZone=document.getElementById(`astJoystickZone`),jBase=document.getElementById(`astJoystickBase`),jKnob=document.getElementById(`astJoystickKnob`),fireBtn=document.getElementById(`astBtnFire`),RADIUS=34,jPointerId=null,jCx=0,jCy=0;function joystickUpdate(dx,dy){let dist=Math.hypot(dx,dy),clamped=Math.min(dist,34),angle=Math.atan2(dy,dx),kx=Math.cos(angle)*clamped,ky=Math.sin(angle)*clamped;if(jKnob.style.transform=`translate(calc(-50% + `+kx+`px), calc(-50% + `+ky+`px))`,Math.min(dist/34,1)<.15){setKey(`left`,!1),setKey(`right`,!1),setKey(`thrust`,!1);return}let deg=angle*180/Math.PI;setKey(`thrust`,ky<-34*.3&&Math.abs(dx)<Math.abs(dy)*2),setKey(`left`,dx<-34*.2),setKey(`right`,dx>34*.2)}function joystickReset(){jPointerId=null,jKnob.style.transform=`translate(-50%,-50%)`,setKey(`left`,!1),setKey(`right`,!1),setKey(`thrust`,!1)}jZone.addEventListener(`pointerdown`,e=>{if(jPointerId!==null)return;e.preventDefault(),jPointerId=e.pointerId,jZone.setPointerCapture(e.pointerId);let r=jBase.getBoundingClientRect();jCx=r.left+r.width/2,jCy=r.top+r.height/2,joystickUpdate(e.clientX-jCx,e.clientY-jCy)},{passive:!1}),jZone.addEventListener(`pointermove`,e=>{e.pointerId===jPointerId&&(e.preventDefault(),joystickUpdate(e.clientX-jCx,e.clientY-jCy))},{passive:!1}),[`pointerup`,`pointercancel`].forEach(ev=>{jZone.addEventListener(ev,e=>{e.pointerId===jPointerId&&joystickReset()})}),fireBtn.addEventListener(`pointerdown`,e=>{e.preventDefault(),fireBtn.setPointerCapture(e.pointerId),setKey(`fire`,!0)},{passive:!1}),[`pointerup`,`pointercancel`,`pointerleave`].forEach(ev=>{fireBtn.addEventListener(ev,()=>setKey(`fire`,!1))})})(),document.addEventListener(`keydown`,e=>{if(!document.getElementById(`winAst`).classList.contains(`hidden`))switch(e.key){case`ArrowLeft`:case`a`:case`A`:setKey(`left`,!0),e.preventDefault();break;case`ArrowRight`:case`d`:case`D`:setKey(`right`,!0),e.preventDefault();break;case`ArrowUp`:case`w`:case`W`:setKey(`thrust`,!0),e.preventDefault();break;case` `:setKey(`fire`,!0),e.preventDefault();break}}),document.addEventListener(`keyup`,e=>{switch(e.key){case`ArrowLeft`:case`a`:case`A`:setKey(`left`,!1);break;case`ArrowRight`:case`d`:case`D`:setKey(`right`,!1);break;case`ArrowUp`:case`w`:case`W`:setKey(`thrust`,!1);break;case` `:setKey(`fire`,!1);break}}),document.getElementById(`ast-startBtn`).onclick=startGame,document.getElementById(`ast-restartBtn`).onclick=startGame,document.getElementById(`astNewGame`).onclick=startGame;function resumeGame(){let sc=document.getElementById(`astStartScreen`);sc.style.display=`none`,raf&&cancelAnimationFrame(raf),paused=!1,raf=requestAnimationFrame(loop),document.getElementById(`ast-startBtn`).textContent=`▶ INICIAR JUEGO`}
// initial render
window.initAst=function(){draw()},window.pauseAst=function(){if(running&&!paused&&!gameOver){paused=!0,raf&&cancelAnimationFrame(raf),raf=null;let sc=document.getElementById(`astStartScreen`);sc.style.display=`flex`,sc.querySelector(`h1`).textContent=`PAUSA`,sc.querySelector(`.sub`).innerHTML=`PUNTUACIÓN: `+score;let btn=document.getElementById(`ast-startBtn`);btn.textContent=`▶ CONTINUAR`,btn.onclick=null,btn.addEventListener(`click`,resumeGame,{once:!0})}},window.astStartNew=function(){startGame()},draw()})();
;